<?php
/**
 * Learning Journey Item Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 */

// Block Name (sluggified).
$block_name = 'learning-journey-item';

$namespace = 'lf';

// Create full block name to use in classes.
$block_name = 'wp-block-' . $namespace . '-' . $block_name;

// setup various classes sent through from $block.
$background = ( empty( $block['backgroundColor'] ) ) ? '' : 'has-' . $block['backgroundColor'] . '-background-color';

$has_background = $background ? 'has-background' : '';

$additional_classes = $block['className'] ?? '';

$all_classes = array(
	$block_name,
	$additional_classes,
);

$classes = implode( ' ', $all_classes );

$inner_block_classes = implode(
	' ',
	array(
		$background,
		$has_background,
		'timeline__item',
	)
);

$lji_title = get_field( 'lji_title' );
$lji_link  = get_field( 'lji_link' );

?>

<div class="<?php echo esc_attr( $classes ); ?>">
	<div class="<?php echo esc_attr( $inner_block_classes ); ?>">

	<?php
	// Hide the link when in admin to stop editors clicking accidentally.
	if ( ! is_admin() ) :
		?>
		<a class="box-link" href="<?php echo esc_url( $lji_link ); ?>" title="<?php echo esc_attr( $lji_title ); ?>"></a>
		<?php
	endif;
	?>
	<span><?php echo esc_html( $lji_title ); ?></span>
	</div>
</div>
