<?php
/**
 * Learning Journey Section Block
 *
 * This block was generated by create-acf-block-json.
 *
 * @package WordPress
 *
 * @param   array $block The block settings and attributes.
 * @param   string $content The block inner HTML (empty).
 * @param   bool $is_preview True during AJAX preview.
 * @param   (int|string) $post_id The post ID this block is saved to.
 */

// Block Name (sluggified).
$block_name = 'learning-journey-section';

$namespace = 'lf';

// Create full block name to use in classes.
$block_name = 'wp-block-' . $namespace . '-' . $block_name;

$ljs_section_number = get_field( 'ljs_section_number' );
$ljs_title          = get_field( 'ljs_title' );
$ljs_last_section   = get_field( 'ljs_last_section' ) ? 'end' : '';
$ljs_title_slug     = strtolower( trim( preg_replace( '/[^A-Za-z0-9-]+/', '-', $ljs_title ), '-' ) );

$allowed_blocks = array( 'lf/learning-journey-item' );

$all_classes = array(
	$block_name,
	$ljs_last_section,
);

$classes = implode( ' ', $all_classes );

?>

<div id="<?php echo esc_attr( $ljs_title_slug ); ?>" class="<?php echo esc_attr( $classes ); ?>">
	<div class="timeline__section">
		<div class="timeline__header">
			<div class="timeline__number"><?php echo esc_html( $ljs_section_number ); ?></div>
			<div class="timeline__title"><?php echo esc_html( $ljs_title ); ?></div>
		</div>
		<?php
		echo '<InnerBlocks allowedBlocks="' . esc_attr( wp_json_encode( $allowed_blocks ) ) . '" />';
		?>
	</div>
</div>
